### ISSUE TITLE
Please add link to new network-uri-flag package in `.cabal` description

### ISSUE THREAD

**Issue by hvr** [haskell/network-uri#31]
See http://hackage.haskell.org/package/network-uri-flag

The `network-uri-flag` package is a good alternative so ppl don't have to copy'n'paste the `flag(network-uri)` boilerplate into every package wanting to support `network-2.5`, so IMHO this should be mentioned as an alternative in `network-uri.cabal`'s description.

PS: If you prefer, I can submit a PR

**Comment by ezrakilty** [comment]
Great idea! I revised the description in https://github.com/haskell/network-uri/commit/c6441d19e3ef4286a0c4ab92ee6977ff6ba27f17

What do you think?

**Comment by hvr** [comment]
@ezrakilty wording looks fine to me; I've just added a minor note re hyperlink-markup

Btw, I suspect that the `==` markup won't work yet on Hackage (we need to fix that on Hackage!), but that's no reason not to use it... Hackage needs to support it! :-)

**Comment by hvr** [comment]
@ezrakilty is a new release of `network-uri` planned any time soon? If not, do you mind if I revise the meta-data on Hackage to include c6441d1?

**Comment by ezrakilty** [comment]
Apologies for the delay. The continuous build has been broken for Cabal reasons that I haven't understood, which is what has kept me from dealing with this.

Are you saying that it's possible to update the metadata without doing a release? If so, I didn't realize that, and yes, we should do that. If you can do it straight away, then yes, feel free. Otherwise I'll try to get to it in the next day or so.

**Comment by hvr** [comment]
@ezrakilty I'll take a look at the travis issue first (next time, please nag me if you run into problems with Travis :-) )

**Comment by ezrakilty** [comment]
Ah, I only just made the connection that you're the one behind the travis integration. Terrific! Thank you for bailing me out.

Your edits to the metadata look great.

One small thing on the Travis script: The old script had a "head" version which always built against the latest version of GHC, which was good because it would go off when there was some kind of breaking change. I'll take a stab at integrating that into the new script.

**Comment by hvr** [comment]
Adding `head` should be straightforward (just extend the `tested-with`-line, and re-run the script generator tool):

```diff
diff --git a/.travis.yml b/.travis.yml
index 76099b5..5183db4 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,6 +50,12 @@ matrix:
     - compiler: "ghc-8.2.1"
     # env: TEST=--disable-tests BENCH=--disable-benchmarks
       addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.1], sources: [hvr-ghc]}}
+    - compiler: "ghc-head"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - compiler: "ghc-head"
 
 before_install:
  - HC=${CC}
diff --git a/network-uri.cabal b/network-uri.cabal
index 2093978..e4810e3 100644
--- a/network-uri.cabal
+++ b/network-uri.cabal
@@ -44,7 +44,7 @@ maintainer:          ezra@ezrakilty.net
 category:            Network
 build-type:          Simple
 cabal-version:       >=1.10
-tested-with: GHC==8.2.1, GHC==8.0.2, GHC==7.10.3, GHC==7.8.4, GHC==7.6.3, GHC==7.4.2, GHC==7.2.2, GHC==7.0.4
+tested-with: GHC==8.3.*, GHC==8.2.1, GHC==8.0.2, GHC==7.10.3, GHC==7.8.4, GHC==7.6.3, GHC==7.4.2, GHC==7.2.2, GHC==7.0.4
 
 library
   exposed-modules:
```

Btw, there's also a neat Travis feature you may be interested in enabling: https://docs.travis-ci.com/user/cron-jobs/
